<main>

    <!-- <section>
        <a href="\..\..\aplication\index\index.phtml">
            <button class="btn btn-success">Voltar</button>
        </a>
    </section> -->
	
    <h2 class="mt-3">Editar Ordem</h2>

	<form name="form" method="POST" 
      action="/application/index/edit/<?php echo $this->ordem->getId();?>">
	<input type="hidden" name="id" value="<?php echo $this->ordem->getId();?>"/>


	<div class="form-group">
        <label>Título</label>
        <input type="text" class="form-control" name="titulo" value="<?php echo $this->ordem->getTitulo();?>">
    </div>

	
	<div class="form-group">
		<label>Descrição</label>
		<textarea class="form-control" name="descricao" rows="5"><?php echo $this->ordem->getDescricao();?></textarea>
	</div>
	
	<div class="form-group">
		<label>Status</label>
		
		<div>
			<div class="form-check form-check-inline">
				<label>
					<input type="radio" name="ativo" value="s" checked> Ativo
				</label>
			</div>
		
			<div class="form-check form-check-inline">
				<label>
					<input type="radio" name="ativo" value="n" <?=$this->ordem->getAtivo() == 'n' ? 'checked' : ''?>> Inativo
				</label>
			</div>
		</div>

	</div>
	
	<button class="btn btn-success" type="submit">Atualizar</button>
</form>
</main>