<section>
    <a href="/application/index/create">
        <button class="btn btn-success">Nova Ordem</button>
    </a>
    <br><br>
</section>

<section>
<table id='tabela' class="table bg-light mt-3">
    <thead>
        <tr>
            <th>ID</th>
            <th>Título</th>
            <th>Descrição</th>
            <th>Status</th>
            <th>Data</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->ordens as $o): ?>
        <tr>
            <td><?php echo $o->getId();?></td>    
            <td><?php echo $o->getTitulo();?></td>    
            <td><?php echo $o->getDescricao();?></td>
            <td><?php echo ($o->getAtivo() == 's' ? 'Ativo' : 'Inativo');?></td>
            <td><?php echo (date('d/m/Y à\s H:i:s', strtotime($o->getData())));?></td>
            <td>
            <a href="/application/index/edit/<?php echo $o->getId();?>">
                <button type="button" class="btn btn-primary">Editar</button>
            </a>
            <!-- CONFIRMAR EXCLUSÃO USANDO SCRIPT JAVASCRIPT -->
            <a href="/application/index/delete/<?php echo $o->getId();?>">
                <button type="button" class="btn btn-danger" onclick="return confirm('Tem certeza que deseja apagar esta ordem?')">Excluir</button>
            </a>
        </td>
        </tr>
        <?php endforeach;?>
    </tbody>
</table>
</section>

</script>