<section>
    <a href="/application/index/create">
        <button class="btn btn-success">Nova Ordem</button>
    </a>
    <br><br>
</section>

<section>
<table id='tabela' class="table bg-light mt-3">
    <thead>
        <tr>
            <th>ID</th>
            <th>Título</th>
            <th>Descrição</th>
            <th>Status</th>
            <th>Data</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->ordens as $o): ?>
        <tr>
            <td><?php echo $o->getId();?></td>    
            <td><?php echo $o->getTitulo();?></td>    
            <td><?php echo $o->getDescricao();?></td>
            <td><?php echo ($o->getAtivo() == 's' ? 'Ativo' : 'Inativo');?></td>
            <td><?php echo (date('d/m/Y à\s H:i:s', strtotime($o->getData())));?></td>
            <td>
            <a href="/application/index/edit/<?php echo $o->getId();?>">
                <button type="button" class="btn btn-primary">Editar</button>
            </a>
            <!-- CONFIRMAR EXCLUSÃO USANDO SCRIPT JAVASCRIPT -->
            <a href="/application/index/delete/<?php echo $o->getId();?>">
                <button type="button" class="btn btn-danger" onclick="return confirm('Tem certeza que deseja apagar esta ordem?')">Excluir</button>
            </a>

            <!-- CONFIRMAR EXCLUSÃO USANDO função javascript confirmacao() -->
                <button type="button" class="btn btn-danger" onclick="confirmacao(<?php echo $o->getId();?>)">Excluir</button>
        
            <!-- CONFIRMAR EXCLUSÃO USANDO JQUERY -->
            <!-- <a href="/application/index/delete/<?php echo $o->getId();?>"
                data-confirm="Are you sure you want to delete?">Excluir</a>
            </a> -->
            
        </td>
        </tr>
        <?php endforeach;?>
    </tbody>
</table>
</section>

<script language="Javascript">
	function confirmacao(id) {
		var r = confirm("Tem certeza que deseja apagar esta ordem?");
		if (r == true) {
			window.location.href = "/application/index/delete/"+id;
			alert("ORDEM EXCLUÍDA")
		}
	}

// JQuery
/*     $(document).ready(function() {
        $('a[data-confirm]').click(function(ev) {
            var href = $(this).attr('href');

            if (!$('#dataConfirmModal').length) {
                $('body').append('<div id="dataConfirmModal" class="modal" role="dialog" aria-labelledby="dataConfirmLabel" aria-hidden="true"><div class="modal-header"><button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button><h3 id="dataConfirmLabel">Please Confirm</h3></div><div class="modal-body"></div><div class="modal-footer"><button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button><a class="btn btn-primary" id="dataConfirmOK">OK</a></div></div>');
            } 
            $('#dataConfirmModal').find('.modal-body').text($(this).attr('data-confirm'));
            $('#dataConfirmOK').attr('href', href);
            $('#dataConfirmModal').modal({show:true});
            return false;
        });
    }); */

</script>